version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-music
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ristov12345@
      POSTGRES_DB: music
    ports:
      - "5432:5432"